#!/usr/bin/env bash
#
# Vendor the Phosphor icon subset the admin UI uses into one inline SVG sprite.
#
# Usage:
#   scripts/build-icons.sh                  # regenerate templates/icons.html
#   scripts/build-icons.sh --check          # fail if the sprite is out of date
#
# Why a sprite and not the icon font: the CSP set in main.go is
# `default-src 'self'` with no font-src or img-src beyond self, so the CDN
# webfont the design prototypes load would be blocked by our own header. And
# dsforms ships as one binary with no runtime network dependency — an icon set
# fetched from unpkg on every page load is the opposite of that.
#
# The sprite is embedded in every page via templates/base.html. At ~70 glyphs it
# is roughly 25KB raw, well under 8KB gzipped, and costs no extra request.
#
# Icons are MIT licensed (c) Phosphor Icons — see static/LICENSE-phosphor.
#
# Requires curl. Network access only when regenerating; the committed sprite is
# what builds use.

set -euo pipefail

VERSION="2.1.1"
BASE="https://unpkg.com/@phosphor-icons/core@${VERSION}/assets/regular"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/templates/icons.html"

# The icons referenced by the admin templates and the landing page.
#
# Kept as an explicit list rather than scraped from the templates at build time:
# a typo'd icon name should fail loudly here, not silently ship a blank glyph.
# That is not hypothetical — the design handoff calls for `envelope-simple-slash`
# on the quarantine "Block sender" button, and no such icon exists in Phosphor at
# any version, so it rendered blank in the prototype too. It is substituted with
# `user-minus`, which also pairs with the `user-check` on the adjacent
# "Allowlist sender" button.
ICONS="
arrow-bend-up-left arrow-u-up-left arrow-u-up-right arrow-up-right
book-open brackets-curly bug
caret-double-left caret-double-right caret-down caret-left caret-right caret-up
chart-line-up chat-circle-dots check check-circle clipboard-text cloud-arrow-up copy
database discord-logo dots-three download-simple
envelope envelope-open envelope-simple
file-csv file-html fingerprint flag funnel
gauge gear-six github-logo hard-drives
link list list-numbers lock-key
magnifying-glass megaphone
package paper-plane-tilt plus plus-circle prohibit
question
selection-slash shield-check shield-warning sidebar-simple sign-out slack-logo
sliders-horizontal star
terminal-window text-aa trash tray tray-arrow-down
upload-simple user-check user-circle user-focus user-minus users-three
warning webhooks-logo x
"

check_mode=0
[ "${1:-}" = "--check" ] && check_mode=1

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

{
	echo '{{define "icons"}}'
	echo '<!-- Phosphor icons (regular), MIT (c) Phosphor Icons. Generated by'
	echo "     scripts/build-icons.sh from @phosphor-icons/core@${VERSION} — do not edit by hand."
	echo '     Referenced as <svg class="i"><use href="#ph-NAME"/></svg>. -->'
	echo '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">'

	for name in $ICONS; do
		src="${tmp}/${name}.svg"
		if ! curl -sSf --max-time 20 -o "$src" "${BASE}/${name}.svg"; then
			echo "error: icon '${name}' not found at ${BASE}/${name}.svg" >&2
			exit 1
		fi
		# Phosphor ships each icon as a single-line
		#   <svg xmlns=... viewBox="0 0 256 256" fill="currentColor">PATHS</svg>
		# Strip the wrapper and re-emit the paths inside a <symbol>. fill is
		# dropped so the glyph inherits currentColor from the use site.
		inner="$(sed -e 's|^.*<svg[^>]*>||' -e 's|</svg>[[:space:]]*$||' "$src" | tr -d '\n')"
		if [ -z "$inner" ]; then
			echo "error: icon '${name}' downloaded empty" >&2
			exit 1
		fi
		printf '<symbol id="ph-%s" viewBox="0 0 256 256">%s</symbol>\n' "$name" "$inner"
	done

	echo '</svg>'
	echo '{{end}}'
} >"${tmp}/icons.html"

if [ "$check_mode" -eq 1 ]; then
	if ! diff -q "${tmp}/icons.html" "$OUT" >/dev/null 2>&1; then
		echo "templates/icons.html is out of date — run scripts/build-icons.sh" >&2
		exit 1
	fi
	echo "templates/icons.html is up to date"
	exit 0
fi

mv "${tmp}/icons.html" "$OUT"
echo "wrote $OUT ($(grep -c '<symbol' "$OUT") icons, $(wc -c <"$OUT" | tr -d ' ') bytes)"
