#!/usr/bin/env bash
#
# Generate CHANGELOG.md from git tags and Conventional Commit messages.
#
# Usage:
#   scripts/changelog.sh > CHANGELOG.md
#
# Output follows the Keep a Changelog format: one section per SemVer tag
# (newest first), commits grouped by conventional-commit type. Commits since
# the latest tag appear under "Unreleased". The whole file is regenerated from
# history every run, so it is safe to overwrite — there is nothing to merge.
#
# No dependencies beyond git and awk (POSIX). Runs the same locally and in CI.

set -euo pipefail

# emit_section RANGE TYPE_REGEX HEADING
# Prints "### HEADING" plus one bullet per matching commit, or nothing if none.
emit_section() {
	range="$1"
	type_re="$2"
	heading="$3"

	# %x1f is the ASCII unit separator — an unambiguous field delimiter that
	# cannot appear in a commit subject.
	body=$(git log "$range" --no-merges --pretty=format:'%h%x1f%s' 2>/dev/null \
		| awk -v re="$type_re" -F'\037' '
			{
				msg = $2
				# Match: type, optional (scope), optional !, colon, space.
				if (match(msg, "^(" re ")(\\([^)]*\\))?!?: ")) {
					desc = substr(msg, RLENGTH + 1)
					printf "- %s (%s)\n", desc, $1
				}
			}' \
		| grep -v 'update CHANGELOG' || true)

	if [ -n "$body" ]; then
		printf '### %s\n%s\n\n' "$heading" "$body"
	fi
}

# emit_release RANGE HEADER
# Prints "## HEADER" with all non-empty type sections, or nothing if the range
# has no conventional commits.
emit_release() {
	range="$1"
	header="$2"

	content=$(
		emit_section "$range" "feat" "Features"
		emit_section "$range" "fix" "Bug Fixes"
		emit_section "$range" "perf" "Performance"
		emit_section "$range" "refactor" "Refactoring"
		emit_section "$range" "docs" "Documentation"
		emit_section "$range" "test" "Tests"
		emit_section "$range" "chore|build|ci|style" "Chores"
	)

	if [ -n "$content" ]; then
		printf '## %s\n\n%s' "$header" "$content"
	fi
}

printf '# Changelog\n\n'
printf 'All notable changes to this project are documented in this file.\n\n'
printf 'The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),\n'
printf 'and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\n'
printf 'This file is generated by `scripts/changelog.sh`; do not edit it by hand.\n\n'

tags=$(git tag --sort=-version:refname)
latest=$(printf '%s\n' "$tags" | head -n1)

# Unreleased: commits after the most recent tag (omitted when there are none).
if [ -n "$latest" ]; then
	unreleased=$(emit_release "${latest}..HEAD" "[Unreleased]")
	[ -n "$unreleased" ] && printf '%s\n\n' "$unreleased"
fi

# One section per tag, newest first. Each tag's range is previous_tag..tag;
# the oldest tag covers every commit reachable from it. Capture each release and
# print with a trailing blank line — command substitution strips the trailing
# newlines emit_release would otherwise carry, so releases would run together.
print_release() {
	rel=$(emit_release "$1" "$2")
	[ -n "$rel" ] && printf '%s\n\n' "$rel"
	return 0
}

prev=""
for tag in $tags; do
	if [ -n "$prev" ]; then
		date=$(git log -1 --format=%ad --date=short "$prev")
		print_release "${tag}..${prev}" "[${prev#v}] - ${date}"
	fi
	prev="$tag"
done
if [ -n "$prev" ]; then
	date=$(git log -1 --format=%ad --date=short "$prev")
	print_release "$prev" "[${prev#v}] - ${date}"
fi
